# Generated by Django 5.1.1 on 2024-10-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='data_aula',
            new_name='data_comentario',
        ),
        migrations.AlterField(
            model_name='anexoaula',
            name='extensao',
            field=models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('WAV', 'WAVE')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='anexoaula',
            name='tipo',
            field=models.CharField(choices=[('A', 'Arquivo'), ('F', 'Foto'), ('S', 'Audio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='anexocomentario',
            name='extensao',
            field=models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('WAV', 'WAVE')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='anexocomentario',
            name='tipo',
            field=models.CharField(choices=[('A', 'Arquivo'), ('F', 'Foto'), ('S', 'Audio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(choices=[('P', 'Propria'), ('O', 'Opiniao')], max_length=1),
        ),
    ]
