# Generated by Django 5.1.1 on 2024-10-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_data_aula_comentario_data_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoaula',
            name='extensao',
            field=models.CharField(choices=[('P', 'PDF'), ('J', 'JPG'), ('W', 'WAVE')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='anexocomentario',
            name='extensao',
            field=models.CharField(choices=[('P', 'PDF'), ('J', 'JPG'), ('W', 'WAVE')], max_length=3, null=True),
        ),
    ]
